import Head from "next/head";
import { request } from "@/lib/datocms";

export async function getStaticProps() {
  const data = await request({
    query: `
      {
        allPosts {
          id
          title
        }
      }
    `,
  });

  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold">Hello DatoCMS!</h1>
        <pre>{JSON.stringify(data, " ", 2)}</pre>
      </main>
    </div>
  );
}
